### ISSUE TITLE
The BUILDS_CACHE and JOBS_CACHE needs to implement cache invalidation

### ISSUE THREAD

**Issue by chmanchester** [mozilla/mozilla_ci_tools#273] opened 2015-07-01 17:43 UTC
I noted in https://github.com/armenzg/mozilla_ci_tools/pull/257/files#r33635885 that the way we're using the jobs cache will be problematic if we were to use mozci for a long running service (such as if we wanted to use this function in trigger-bot). Some option to invalidate the cache on demand would be sufficient.

**Comment by vaibhavmagarwal** [comment] 2015-07-01 17:47
I agree. We should probably have the cache only for expensive operations like --coalesced mode. Or we can have the cache off by default and do the caching with --cache flag. Whichever seems suitable.

**Comment by adusca** [comment] 2015-07-01 18:03
This is a graph of the script's running time before JOBS_CACHE: http://explique.me/images/graph_master.svg

This is a case with only 7 buildernames, and adding the caches made the script 5 times faster (see issue #200 for complaints about the previous behaviour). Since the page is not updated that frequently, we do not lose anything by caching by default on a normal script run, the problem is for long running services. Having a way to clean it or turn it off will be useful then.

**Comment by vaibhavmagarwal** [comment] 2015-07-02 00:31
Now that we are supporting fetching status from Treeherder Api, I think we can remove the caching part from buildapi, because all the jobs that are scheduled are present in TH-api. The whole point of using buildapi is that we want to have accurate data, else we can use Treeherder. @jgraham too mentioned in his comment: https://github.com/armenzg/mozilla_ci_tools/issues/200#issue-76431810 that caching in buildapi is an interim solution till TH functionality comes around. @armenzg, @chmanchester, @adusca what do you think?

**Comment by armenzg** [comment] 2015-07-03 16:46
We want to keep the cache by default and optionally disable it. Too much of a perf hit (In the case of buildapi).

Once the buildbot scheduling moves to TaskCluster (by end of Q3), Treeherder will not have as many status issues and we will be able to use it as the default data source for mozci.

It would also be cool to have a script to compare the discrepancies between the two.

**Comment by armenzg** [comment] 2016-02-29 19:38
In general we will be switching to using Treeherder as our source of jobs instead of Buildapi hence closing this issue.

**Closed by armenzg** 2016-02-29 19:38 UTC
